### ISSUE TITLE
Replace @p1 by params values

### ISSUE THREAD

**Issue by tolares** [oakio/Sqlify#1]
While trying to use your lib I faced an issue, how can I replace the @p values by the actual params value.
Exemple :
`Sql.Select(table.name).From(table)
                .Where(table.Id.In(Ids))`
Today it will generate when applying the ToString() method.
`SELECT table.name FROM table WHERE table.Id IN @p1`

Does I'm missing something ? 

Thanks !

**Comment by oakio** [comment]
Sorry, but now it's impossible.

`Sqlify` is by design use params to prevent **SQL-injection attack**, this is main idea.

In addition params can improve performance of queries (caching parameterized query plans) https://docs.microsoft.com/en-us/previous-versions/tn-archive/cc293623(v=technet.10).

**Comment by oakio** [comment]
But you can implement own `InConstValuesPredicate` (see https://github.com/oakio/Sqlify/blob/master/src/Sqlify/Core/Predicates/InPredicate.cs) class, where `Format` method will be use values instead params.

Also create extension method for `Column<T>` for this new predicate.

**Comment by tolares** [comment]
Okay thanks for the explanation ! 
Unfortunatly since you have sealed them I can't extend my class the easiest solution will be to do a fork I think

**Comment by oakio** [comment]
Try this:
```csharp
public class InValuesPredicate<T> : Predicate
{
    private readonly Column<T> _left;
    private readonly IReadOnlyCollection<T> _right;

    public InValuesPredicate(Column<T> left, IReadOnlyCollection<T> right)
    {
        _left = left;
        _right = right;
    }

    public override void Format(ISqlWriter writer)
    {
        _left.Format(writer);
        writer.Append(" IN (");
        bool appendComma = false;

        foreach (T value in _right)
        {
            if (appendComma)
            {
                writer.Append(", ");
            }

            writer.Append(value?.ToString());

            appendComma = true;
        }
        writer.Append(")");
    }
}
```
```csharp
public static class MyColumnExtensions
{
    public static Predicate InValues<T>(this Column<T> column, IReadOnlyCollection<T> values) => new InValuesPredicate<T>(column, values);
}
```
Usage:
```csharp
Sql
    .Select(table.name)
    .From(table) 
    .Where(table.Id.InValues(Ids));
```
